### ISSUE TITLE
Update Gem

### ISSUE THREAD

**Issue by ghost** [18F/us_web_design_standards_gem#21]
Hi All

I needed to know if is repo will be updated in the future?Also I was interested in maintaining it.Any how to guides would be useful as I haven't maintained a gem file before.Any help or guidance would be appreciated.

Thanks,
Neil

**Comment by pkarman** [comment]
Hi @neilmartis 

There are no plans to update this repo. It has been deprecated. Largely the issue with it is that it does not play nicely with both Jekyll and Rails, and so wasn't serving well as a general-purpose gem.

See https://github.com/18F/uswds-rails-gem (for Rails) and https://github.com/18F/us_web_design_standards_gem/pull/18 (for Jekyll).

Per our policy we do not delete repos, but there are currently no plans to continue maintaining this one. Feel free to fork and maintain as you will!

**Comment by ghost** [comment]
@pkarman Hi Peter Thanks a lot for the information and gem link as well.RubyGems does not have the current USWDS gem updated it still shows the old version as per this repo. Thanks a ton.

**Comment by ghost** [comment]
@pkarman Does it work both with Jekyll and ruby on rails ?

**Comment by pkarman** [comment]
@neilmartis the gem `us_web_design_standards_gem` in this repo does *not* work with both Jekyll and Rails.

This gem (https://github.com/18F/uswds-rails-gem) is the equivalent for Rails, and is maintained by 18F. It is not currently published to RubyGems site.

RubyGems has 2 USWDS gems on it now:

https://rubygems.org/gems/us_web_design_standards_ror  <-- a fork of 18F, not maintained by us

https://rubygems.org/gems/us_web_design_standards <-- the published gem from this repo. We have no plans to update this, per my comments elsewhere on this ticket.
