### ISSUE TITLE
Mixins, functions not working correctly?

### ISSUE THREAD

**Issue by webinista** [18F/us_web_design_standards_gem#4]
I tried to integrate this gem in a Rails application, but the mixins, variables, and functions couldn't be found. Using these files without including them as a gem works fine, although I did have to update a few paths. I suspect paths may be the problem in the gem as well. I tried adjusting them, however, and still received the same error.

Using Rails 4.2.4.

**Comment by mbland** [comment]
Can you post the error output here?

Also calling on @blacktm and possibly @adelevie to chip in, as I'm far more versed in Jekyll than Rails.

**Comment by webinista** [comment]
```
 Showing /Users/tiffany/[appname redacted]/app/views/layouts/basic.html.erb where line #10 raised:1

 Undefined mixin 'unstyled-list'.
      &-menu {
          @include unstyled-list();
          @include transition (all 0.2s ease-in-out);
          background: $color-white;
          border: 1px solid $color-gray-lighter;
          cursor: pointer;
```

The application trace is:
    app/assets/stylesheets/application.scss:14:in 'unstyled-list'
    app/assets/stylesheets/application.scss:14
    app/views/layouts/basic.html.erb:10:in _app_views_layouts_basic_html_erb___38243940_22836'
    app/controllers/web_controller.rb:181:in 'login'

In the `application.css.scss` file, I have this:

```
 /*
  * = require us_web_design_standards
  * = require us_web_design_standards_fonts
  */
```

**Comment by shanear** [comment]
@webinista by including the files in the rails manifest, you lose access to scss stuff like variables/mixins/etc.

This can be fixed by importing the files into your main sass file instead of into the Rails manifest:

```
#_main.scss

@import "us_web_design_standards";
@import "us_web_design_standards_fonts";
```

maybe we should change this in the docs.

**Comment by webinista** [comment]
Thanks @shanear. That worked. This probably should updated in the docs. File a pull request?

**Comment by webinista** [comment]
Closing issue since we have a fix.
