### ISSUE TITLE
Wrong image assets URLs

### ISSUE THREAD

**Issue by andriytyurnikov** [18F/us_web_design_standards_gem#5]
For some reason images referenced as:

```
url(../img/*.png)
```

And not /assets/images.
Obviously image elements don't work in rails

**Comment by andriytyurnikov** [comment]
But those can be accessed as `/assets/arrow-down.svg` for example. So Rails pipeline integration is ok - it is path issue.

**Comment by andriytyurnikov** [comment]
Same with fonts

**Comment by pkarman** [comment]
does #7 fix this?

**Comment by pkarman** [comment]
Please see #20 -- the new Rails gem should fix this.
