### ISSUE TITLE
Rename repo web-design-standards-gem

### ISSUE THREAD

**Issue by maya** [18F/us_web_design_standards_gem#8]
Since the main repo is `web-design-standards`, it might be nice to follow the naming convention with this repo as `web-design-standards-gem` to keep it consistent.

Other related repos do this with `web-design-standards-assets` and `web-design-standards-drupal`.

**Comment by shanear** [comment]
+1

**Comment by rogeruiz** [comment]
This is a good idea. Let's document all the places where the name would need to change in this Issue.

**Comment by nickjs** [comment]
Any Gemfiles of any other projects that use this will need to be updated, though those projects won't immediately break

**Comment by pkarman** [comment]
This gem is deprecated. No need to change the name.

**Comment by shanear** [comment]
@pkarman what is the plan going forward for consumers of the gem? is that documented anywhere?

**Comment by pkarman** [comment]
There is no plan. You can read the history of that decision here: https://github.com/18F/us_web_design_standards_gem/issues/15#issuecomment-203564667
